INSERT INTO PRODUCTS (ID,NAME,SALES_UNITS,STOCK_S,STOCK_M,STOCK_L) VALUES (1,'V-NECH BASIC SHIRT', 100, 4, 9, 0);
INSERT INTO PRODUCTS (ID,NAME,SALES_UNITS,STOCK_S,STOCK_M,STOCK_L) VALUES (2,'CONTRASTING FABRIC T-SHIRT', 50, 35, 9 ,9);
INSERT INTO PRODUCTS (ID,NAME,SALES_UNITS,STOCK_S,STOCK_M,STOCK_L) VALUES (3,'RAISED PRINT T-SHIRT', 80, 20, 2, 20);
INSERT INTO PRODUCTS (ID,NAME,SALES_UNITS,STOCK_S,STOCK_M,STOCK_L) VALUES (4,'PLEATED T-SHIRT', 3, 25, 30, 10);
INSERT INTO PRODUCTS (ID,NAME,SALES_UNITS,STOCK_S,STOCK_M,STOCK_L) VALUES (5,'CONTRASTING LACE T-SHIRT', 650, 4, 0, 1);
INSERT INTO PRODUCTS (ID,NAME,SALES_UNITS,STOCK_S,STOCK_M,STOCK_L) VALUES (6,'SLOGAN T-SHIRT', 20, 9, 2, 5);